# Generated by Django 5.0.3 on 2024-03-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac_address',
            new_name='hostname',
        ),
    ]
